# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-12-03 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181203_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysearch',
            name='publish_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mysearch',
            name='created_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
