# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-12-04 15:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_mysearch_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysearch',
            old_name='filename',
            new_name='file',
        ),
        migrations.AddField(
            model_name='mysearch',
            name='img',
            field=models.ImageField(default=datetime.datetime(2018, 12, 4, 15, 21, 36, 859000, tzinfo=utc), upload_to='/.img'),
            preserve_default=False,
        ),
    ]
