# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-12-04 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181204_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysearch',
            name='file',
        ),
        migrations.RemoveField(
            model_name='mysearch',
            name='img',
        ),
    ]
