# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-12-08 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181205_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysearch',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mysearch',
            name='model_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mysearch',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
