# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-12-08 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_mysearch_publish_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysearch',
            name='created_data',
        ),
    ]
