# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-12-15 06:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181212_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysearch',
            name='img',
            field=models.ImageField(blank=True, upload_to='./img'),
        ),
        migrations.AlterField(
            model_name='mysearch',
            name='publish_data',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 15, 6, 56, 48, 410000, tzinfo=utc)),
        ),
    ]
