# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-12-15 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20181215_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysearch',
            name='content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='mysearch',
            name='publish_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
